config/routes.rb
Rails.application.routes.draw do

  root to: 'questions#index'
  devise_for :users

  resources :questions do
    resources :comments, only: [:create]
    resources :answers, only: [:create]
    resource :vote, only: [:create, :destroy]
  end

  resources :answers do
    resources :comments
    resource :vote, only: [:create, :destroy]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/answer.rb
class Answer < ApplicationRecord

  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :body, presence: true, allow_blank: false

  def voted_by? (user)
    votes.exists?(user: user)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true, allow_blank: false
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  has_many :answers, :dependent => :destroy
  has_many :comments, as: :commentable, :dependent => :destroy
  has_many :votes, as: :voteable, :dependent => :destroy

  validates :title, presence: true, allow_blank: false
  validates :body, presence: true, allow_blank: false

  def voted_by? (user)
    votes.exists?(user: user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :votes
has_many :questions
has_many :answers
has_many :comments

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voteable, polymorphic: true
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    if params[:question_id].present?
      question = Question.find(params[:question_id])
      answer = question.answers.new(answers_params)
      if answer.save
        redirect_to question
      else
        @errors = answer.errors.full_messages
        redirect_to question, notice: 'No se permiten comentarios ni respuestas en blanco o vacias, intente de nuevo'
      end
    end 
  end

  def answers_params
    params.require(:answer).permit(:body).merge(user: current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  after_action :store_location

  def store_location
    # store last url as long as it isn't a /users path
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if params[:question_id].present?
      question = Question.find(params[:question_id])
      coment = question.comments.new(comments_params)
      if coment.save
        redirect_to question
      else
        @errors = coment.errors.full_messages
        redirect_to question, notice: 'No se permiten comentarios ni respuestas en blanco o vacias, intente de nuevo'
      end
    elsif params[:answer_id].present?
      answer = Answer.find(params[:answer_id])
      coment = answer.comments.new(comments_params)
      if coment.save
        redirect_to answer.question
      else
        @errors = coment.errors.full_messages
        redirect_to answer.question, notice: 'No se permiten comentarios ni respuestas en blanco o vacias, intente de nuevo'
      end
    else
      @errors = answer.errors.full_messages
    end
  end


  def comments_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @questions = Question.all
    if params[:title].present?
      @questions = @questions.where("title ILIKE ?", "%#{params[:title]}%")
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    if @question.save
      redirect_to questions_path
    else
      @errors = @question.errors.full_messages
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)

    redirect_to questions_path
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private
    def question_params
      params.require(:question).permit(:title, :body).merge(user_id: current_user.id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def create
    if params[:question_id].present?
      question = Question.find(params[:question_id])
      question.votes.create(user: current_user)

      redirect_to question
    elsif params[:answer_id].present?
      answer = Answer.find(params[:answer_id])
      answer.votes.create(user: current_user)

      redirect_to answer.question
    end
  end

  def destroy
    if params[:question_id].present?
      question = Question.find(params[:question_id])
      question.votes.where(user: current_user).take.try(:destroy)

      redirect_to question
    elsif params[:answer_id].present?
      answer = Answer.find(params[:answer_id])
      answer.votes.where(user: current_user).take.try(:destroy)

      redirect_to answer.question
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverstack</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-inverse" id="index">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% unless signed_in?%>
          <a class="navbar-brand" href="/">Flowoverstack</a>
          <% end %>
          <% if signed_in? %>
          <a class="navbar-brand" href="/"> Hola! <%= User.find_by(id: [current_user.id]).email%></a>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <form class="navbar-form navbar-right">

            <%= form_tag questions_path, method: :get do %>
              <div class="form-group">
                <%= text_field_tag :title, params[:title], class: "form-control", placeholder: "Concepto" %>
              </div>
                <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
            <% end %>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <% unless signed_in? %>
            <li><a href="/users/sign_up">Registrarse</a></li>
            <li><a href="/users/sign_in">Ingresar</a></li>
            <% end %>
            <% if signed_in? %>
            <li><%= link_to 'Salir', destroy_user_session_path, method: :delete, class: "btn-default-md" %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

<% if @errors %>
  <div class="error_messages">
    <ul>
      <% @errors.each do |error| %>
      <li style="color:red; font-size:25px;"><%= error %></li>
      <% error %>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.text_field :title, class: "form-control input-lg", placeholder: "Title" %>
</div>
<div class="form-group">
  <%= f.text_area :body, class: "form-control input-lg", placeholder: "Description" %>
</div>

<%= f.submit "Submit", class: "btn btn-warning btn-lg btn-block" %>

<% end %>

app/views/questions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Edita la Pregunta</h1>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container" style="margin-top:80px;">
  <div class="row">
    <div class="col-md-12">
      <h1 class="index">Entradas Flowoverstack</h1>

      <% if signed_in? %>
        <div class="text-right">
          <%= link_to "Hacer Nueva Pregunta", new_question_path, class: "btn btn-warning btn-lg" %>
        </div>
      <% end %>

      <% unless signed_in? %>
      <div class="text-right">
        <%= link_to "Hacer Nueva Pregunta", user_session_path, class: "btn btn-warning btn-lg" %>
      </div>
      <% end %>
      <br>
      <br>

      <table class="table table-bordered">
        <tr>
          <th>PREGUNTAS</th>
        </tr>
      <% @questions.each do |question| %>
        <tr>
          <td><%= link_to question.title, question, class: "link-index" %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container" style="margin-top:80px;">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Nueva Pregunta</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container" style="margin-top:80px;">

  <!-- jumbotron que muestra la pregunta  -->
<div class="jumbotron">
  <h2><strong><%= @question.user.email     %></strong></h2>
  <h3><%= markdown(@question.title) %></h3>
  <p><%= markdown(@question.body) %></p>
    <% if signed_in? %>
      <% if current_user.id == @question.user.id %>
        <%= link_to 'Editar', edit_question_path(@question) %>
        <%= link_to 'Borrar', question_path(@question), method: :delete %>
      <% end %>
    <% end %>
  <br>
<br>
    <% if @question.voted_by? current_user %>
      <%= link_to 'Eliminar Voto',question_vote_path(@question), method: :delete %>
      <p>Votos: <%= @question.votes.count %></p>
    <% else %>
      <%= link_to 'Votar!', question_vote_path(@question), method: :post%>
      <p>Votos: <%= @question.votes.count %></p>
    <% end %>
</div>

<!-- Comentarios de las preguntas  -->
<h1><span class="label label-info">Comentarios</span></h1>

<!-- Loop que muestra los comentarios de las preguntas  -->
<% @question.comments.each do |comment| %>
  <p> <%= markdown(comment.body) %> <span class="user"> <%= comment.user.email %></span></p>
  <hr class="comments"/>
<%end %>

<!-- Form para comentar las preguntas -->
<% if signed_in? %>
  <h3>Comentar la Pregunta</h3>

  <p id="notice" style="color:red; font-size:25px;"><%= notice %></p>

  <%= form_for [@question, @question.comments.build] do |f| %>

    <div class="form-group">
      <%= f.text_area :body, class: "form-control", placeholder: "Agregar Comentario"%>
    </div>
      <%= f.submit "Comentar", class: "btn btn-primary" %>
  <% end %>

<% else %>
<div>
  <%= link_to "Comentar Pregunta", user_session_path, class: "btn btn-primary" %>
</div>

<% end %>


<!-- Linea que divide Comentarios de respuestas   -->
<hr class="section-divider"/>

<!-- Titulo de Respuestas -->
<h1><span class="label label-info">Respuestas</span></h1>

<!-- Loop que muestra las respuestas -->
<% @question.answers.each do |answer| %>
  <div class="jumbotron">
    <h3> <%= markdown(answer.body) %> </h3>
    <p>
      <span class="user"><%= answer.user.email %></span>
    </p>

  <br>
<br>
    <% if answer.voted_by? current_user %>
      <%= link_to 'Eliminar Voto',answer_vote_path(answer), method: :delete %>
      <p>Votos: <%= answer.votes.count %></p>
    <% else %>
      <%= link_to 'Votar!', answer_vote_path(answer), method: :post%>
      <p>Votos: <%= answer.votes.count %></p>
    <% end %>

    <hr class="comments"/>

<!-- Loop que muestra los comentarios a las respuestas  -->
  <% answer.comments.each do |comment| %>
    <p> <%= markdown(comment.body) %></p>
    <hr class="comments" />
  <%end %>

<!-- Seccion de comentar las respuestas -->
  <% if signed_in? %>
    <h3>Comentar la Respuesta</h3>

    <p id="notice" style="color:red; font-size:25px;"><%= notice %></p>

    <%= form_for [answer, answer.comments.build] do |f| %>
    <div class="form-group">
      <%= f.text_area :body, class: "form-control", placeholder: "Agregar Comentario a la respuesta"%>
    </div>
    <%= f.submit "Comentar", class: "btn btn-primary" %>
  <% end %>
  <% else %>
    <%= link_to "Comentar Respuesta", user_session_path, class: "btn btn-primary" %>
  <% end %>
  </div>
<%end %>

<!-- Linea que separa respuestas de preguntas para realizar nueva pregunta -->
<hr class="section-divider"/>

<!-- Formulario para responder pregunta  -->
<% if signed_in? %>
  <h3>Responde la Pregunta</h3>

  <p id="notice" style="color:red; font-size:25px;"><%= notice %></p>

  <%= form_for [@question, @question.answers.build] do |f| %>
    <div class="form-group">
      <%= f.text_area :body, class: "form-control", placeholder: "Respuesta"%>
    </div>
    <%= f.submit "Responder", class: "btn btn-primary" %>
  <% end %>
<% else %>
<div>
  <%= link_to "Responder", user_session_path, class: "btn btn-primary" %>
</div>
<% end %>
</div>